RECOVERY_VARIANT := twrp
TW_THEME := portrait_hdpi
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_INJECTTWRP := false
TW_DEVICE_VERSION := DOOGEE X5PRO
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_INCLUDE_FB2PNG := true
TW_HAS_DOWNLOAD_MODE := false
INTERNAL_LOCAL_CLANG_EXCEPTION_PROJECTS := external/busybox/
#TW_USE_TOOLBOX := true

